export default {
    CHANNEL_NOT_NSFW: "This Channel is not marked as NSFW, please mark it as such an rerun this Command.",
    INSUFFICIENT_PERMISSIONS: `You need \`PERMISSIONS\` Permissions to run this Command `,
    ON_COOLDOWN: `\`COMMAND\` is on Cooldown.`,
    ON_COOLDOWN_DESCRIPTION: `\`COMMAND\` has a cooldown of \`COOLDOWN\` \n Wait \`TIME\` berore trying to use it again.`,
    ON_ERROR: `\`COMMAND\` encountered an Error.`,
    NOT_ENOUGH_TAGS: `Not Enough Tags`,
    NOT_ENOUGH_TAGS_DESC: "You need to provide Tags for me to search for.",
    RP_REQUIRE_MENTION: `You need to mention another user.`,
    RP_SELF: `Dont you want to ACTION someone other than yourself?`,
    RP_ME: `Don't ACTION me! ACTION someone else.`,
    MISSING_TITLE: `Missing title. Separate the title and description with a pipe (\`|\`).`,
    SUGGESTION_SENT: "Suggestion sent.",
    INVITE_STRING: "You can invite BOT using this Link",
    ROLL: ":game_die: Rolling AMOUNT DICE...",
}